### PR TITLE
Fix: Gas Cap

### PR DESCRIPTION
**Pull request by TheMarstonConnell**
Added flag to adjust gas for each message, also added flag for changing the gas limit.

### CODE REVIEW

**Comment by BiPhan4** [comment]
Tried to init a provider as at this PR onto testnet. Received error:

flag accessed but not defined: gas-cap
Error: flag accessed but not defined: gas-cap

Added gasCap flag to init which resolved the error. 

I was able to init on test-net but received:

Authorizing hand to transact on my behalf...
RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
Processing stray thread 4.
Adding hand to my claim whitelist...
account sequence mismatch, expected 17849, got 17848: incorrect account sequence

While initialising hands and only ended up with 9 hands. I noticed a few other providers are also missing 1 or 2 hands.

Will need to look further into this. 

@TheMarstonConnell

**Comment by TheMarstonConnell** [comment]
> Tried to init a provider as at this PR onto testnet. Received error:
> 
> 
> 
> flag accessed but not defined: gas-cap
> 
> Error: flag accessed but not defined: gas-cap
> 
> 
> 
> Added gasCap flag to init which resolved the error. 
> 
> 
> 
> I was able to init on test-net but received:
> 
> 
> 
> Authorizing hand to transact on my behalf...
> 
> RPC error -32603 - Internal error: timed out waiting for tx to be included in a block
> 
> Processing stray thread 4.
> 
> Adding hand to my claim whitelist...
> 
> account sequence mismatch, expected 17849, got 17848: incorrect account sequence
> 
> 
> 
> While initialising hands and only ended up with 9 hands. I noticed a few other providers are also missing 1 or 2 hands.
> 
> 
> 
> Will need to look further into this. 
> 
> 
> 
> @TheMarstonConnell 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 


These errors you're getting are unrelated, we occasionally get them with or without this gas cap edit. It's just the nature of RPC endpoints unfortunately. We can loop until the txn for the hand succeeds but that could cause some issues as well in case it always fails.

**Comment by TheMarstonConnell** [comment]
@karnthis how's this `build_info` api route for you?

**Review by BiPhan4 — APPROVED** [review]
Per Marston's response--it all looks good to me!

**Pull request merged**
